controllers/admin_controller.py
from flask import Blueprint, render_template, current_app, request, redirect,url_for
from flask_bcrypt import Bcrypt
admin_bp = Blueprint('admin_bp', __name__)
bcrypt = Bcrypt()


@admin_bp.route("/crud")
def crud():
    return render_template("Admin/Crud.html")


@admin_bp.route("/crud/usuarios")
def inicio_usuarios():
    connection = current_app.connection
    try:

        with connection.cursor() as cursor:
            cursor.execute("SELECT u.ID_USUARIO,p.ID_PERFIL,p.NOMBRE,p.CORREO FROM usuario u INNER JOIN perfil p ON u.ID_PERFIL = p.ID_PERFIL ")
            usuarios = cursor.fetchall()
            return render_template("Admin/usuario/Admin_menu_u.html", usuarios=usuarios)
    except Exception as e:
        return f"Error al obtener usuarios: {e}"
    return render_template("Admin/usuario/Admin_menu_u.html")

#Botones de volver

@admin_bp.route("/volver")
def volver():
    return redirect(url_for('admin_bp.inicio_usuarios'))

@admin_bp.route("/volver_crud")
def volver_crud():
    return render_template("Admin/Crud.html")



@admin_bp.route("/cerrar_sesion")
def cerrar_sesion():
    return render_template("index.html")


@admin_bp.route("/volver_menu")
def volver_menu():
    return render_template("Admin/Inicio_a.html")

@admin_bp.route("/crud/perfil/<int:id_perfil>", methods=["get","post"])
def perfil_usuario(id_perfil):
    connection = current_app.connection
    
    # Cargar la data del perfil
    if request.method == "GET":
        try:
            with connection.cursor() as cursor:
                cursor.execute("""
                    SELECT p.ID_PERFIL, p.NOMBRE, p.CORREO,p.CONTRASENA
                    FROM perfil p
                    WHERE p.ID_PERFIL = %s
                """, (id_perfil,))
                perfil = cursor.fetchone()
                return render_template("Admin/usuario/Editar_u.html", perfil=perfil)
        except Exception as e:
            return f"Error al obtener perfil: {e}"
    # edita la data del perfil dependiendo del boton
    elif request.method == "POST":

        accion = request.form.get("accion")
        if accion == "actualizar":
            actualizar_perfil(id_perfil)
        elif accion == "eliminar":
            eliminar(id_perfil)

        # Luego de actualizar o eliminar, redirigimos o cargamos la lista
        try:
            with connection.cursor() as cursor:
                cursor.execute("SELECT u.ID_USUARIO,p.ID_PERFIL,p.NOMBRE,p.CORREO FROM usuario u INNER JOIN perfil p ON u.ID_PERFIL = p.ID_PERFIL ")
                usuarios = cursor.fetchall()
                return render_template("Admin/usuario/Admin_menu_u.html", usuarios=usuarios)
        except Exception as e:
            return f"Error al obtener usuarios: {e}"

    # Por si acaso no entra en ninguna condición
    return "Método no válido"



def actualizar_perfil(id):
    connection = current_app.connection
    if request.method == "POST":
        
        #Obtenemos los datos del formulario, por el nombre del input
        nombre = request.form.get("nombre")
        correo = request.form.get("correo")
        contrasena = request.form.get("contrasena")
        #Encriptamos la contraseña
        contrasena = bcrypt.generate_password_hash(contrasena).decode('utf-8')
        #En base al id, actualizamos los campos
        try:
            with connection.cursor() as cursor:
                #tomamos lso valores de la funcion
                cursor.execute("UPDATE perfil SET NOMBRE=%s,CORREO=%s, CONTRASENA=%s WHERE ID_PERFIL=%s",(nombre,correo,contrasena,id))
                #Actualizamos en la base de datos
                connection.commit()
        except Exception as e:

            return str(e)

def eliminar(id):
    #Eliminamos de la base de datos
    connection = current_app.connection
    #En base al id, actualizamos los campos
    try:
            with connection.cursor() as cursor:

                #Como tienen una relacion uno(perfil) a muchos(usuario), primero elimianrmos
                #  el perfil de la tabla usuarios
                cursor.execute("DELETE FROM usuario WHERE ID_PERFIL=%s",(id))
                #Luego al eliminamos de los perfiles
                cursor.execute("DELETE FROM perfil WHERE ID_PERFIL=%s",(id))
                #actualizamos en la base de datos
                connection.commit()

    except Exception as e:
            return str(e)
@admin_bp.route("/crud/perfil/crear", methods=["get","post"])
def crear_usuario():

    #Eliminamos de la base de datos
    connection = current_app.connection
    if request.method == "POST":
        nombre = request.form.get("nombre")
        correo = request.form.get("correo")
        contrasena = request.form.get("contrasena")
        #Encriptamos la contrasena
        contrasena = bcrypt.generate_password_hash(contrasena).decode('utf-8')

        if not nombre or not correo or not contrasena:
            return "Faltan datos", 400

        try:

            with connection.cursor() as cursor:
                # Ya sabemos que es un usuario, asi ue hacemos el INSERT en perfiles primero

                # y luego tomaos el id_perfil y lo añadimos a usuario
                cursor.execute("INSERT INTO perfil(NOMBRE,CORREO,CONTRASENA) VALUES (%s,%s,%s)",(nombre,correo,contrasena,))
                cursor.execute("SELECT ID_PERFIL FROM perfil WHERE NOMBRE=%s AND CORREO=%s",(nombre,correo))
                id_perfil = cursor.fetchone()
                id_perfil = id_perfil["ID_PERFIL"]
                cursor.execute("INSERT INTO usuario(ID_PERFIL) VALUES (%s)",(id_perfil,))
                # actualizamos en la base de datos
                connection.commit()
                #Lo retornamos al usuario
                return redirect(url_for('admin_bp.inicio_usuarios'))
                
                
        except Exception as e:
                return str(e)
    #Retornamos la pantalla por default
    return render_template("Admin/usuario/Admin_crear_u.html")

controllers/user_controller.py
from flask import Blueprint, render_template, current_app, request
from flask_bcrypt import Bcrypt

user_bp = Blueprint('user_bp', __name__)
bcrypt = Bcrypt()


@user_bp.route("/registro",methods=["get","post"])
def registro():
    if request.method == "POST":
        #Coneccion con la base de datos
        connection =  current_app.connection
        #Bcrypt
        bcrypt = Bcrypt()

        rol = request.form.get("ROL")

        nombre = request.form.get("NOMBRE")
        correo = request.form.get("CORREO")
        contrasena = request.form.get("CONTRASENA")
        contrasena  = bcrypt.generate_password_hash(contrasena).decode('utf-8')
        
        try:
            with connection.cursor() as cursor:
                if rol == "administrador":

                    cursor.execute("INSERT INTO perfil(NOMBRE,CORREO,CONTRASENA) VALUES (%s,%s,%s)",(nombre,correo,contrasena,))
                    #Sacamos el id del perfil
                    cursor.execute("SELECT ID_PERFIL FROM perfil WHERE NOMBRE=%s AND CORREO=%s",(nombre,correo))
                    id_perfil_admin = cursor.fetchone()
                    id_perfil_admin = id_perfil_admin["ID_PERFIL"]
                    #Tomamos el id del perfil y le asignamos un id de administrador:
                    cursor.execute("INSERT INTO administrador(ID_PERFIL) VALUES (%s)", (id_perfil_admin,))
                    #Este comando guarda LOS CAMBIOS EN LA BASE DE DATOS
                    connection.commit()

                    return render_template("index.html")
                if rol == "usuario":
                    #Insertamos el perfil
                    cursor.execute("INSERT INTO perfil(NOMBRE,CORREO,CONTRASENA) VALUES (%s,%s,%s)",(nombre,correo,contrasena,))
                    
                    #Sacamos el id del perfil
                    cursor.execute("SELECT ID_PERFIL FROM perfil WHERE NOMBRE=%s AND CORREO=%s",(nombre,correo))
                    id_perfil_usuario = cursor.fetchone()
                    id_perfil_usuario = id_perfil_usuario["ID_PERFIL"]
                    #Tomamos el id del perfil y le asignamos un id de administrador:
                    cursor.execute("INSERT INTO usuario(ID_PERFIL) VALUES (%s)", (id_perfil_usuario,))
                    #Este comando guarda LOS CAMBIOS EN LA BASE DE DATOS
                    connection.commit()

                    return render_template("index.html")

        except Exception as e:
            return str(e)


        return render_template("Registro.html")

    
    if request.method == "GET":
        return render_template("Registro.html")

templates/Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/logo.png') }}">
    <!-- Estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Login.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Volver.css') }}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"/>
    <title>Login</title>
</head>
<body>
    <div class = "inicio">
        <div class="header">

            <!--Volver-->
            <div class="header_volver">
                <a class="volver" onClick="window.history.back()">
                    <img src="{{ url_for('static', filename='img/flecha.png') }}" alt=""/>
                </a>
            </div>
            
            <div class="titulo" >
                Inicio sesion - BBQ REAL SMOKE
            </div>
        </div>

        
        <form class="sesion" method="POST">

          <p>Correo:</p>
          <input type="text" placeholder="Correo" name='correo'onChange=""/>

          <p>Contraseña:</p>
          <input type="password" placeholder="Contrasena" name='contrasena' onChange=""/>

          <a href="../pantallas/Registro.html" class="enlace" >
            Registrate 😋
          </a>
          <a href="" class="enlace" >
            Olvide mi contrasena 😱
          </a>
          <button type="submit" >
            Ingresar
          </button>
          
        </form>

        <div class="imagen">
            <div class="title">BBQ EL REAL</div>
            <div class="logo">
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="" />
            </div>
        </div>

    </div>
    
</body>
</html>

templates/Recuperar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="shortcut icon"  type="image/x-icon" href="../img/logo.png">
    <title>Recuperar contrasena</title>
</head>
<body>
    
</body>
</html>

templates/Registro.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="shortcut icon"  type="image/x-icon" href="../img/logotipo.png">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/logo.png') }}">
    <!-- Estilos -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Registro.css') }}">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/Volver.css') }}">
    <title>Registro</title>
</head>
<body>

    <div class = "inicio">

        
        <div class="header_volver">
            <a class="volver" onClick="window.history.back()">
                <img src="{{ url_for('static', filename='img/flecha.png') }}" alt=""/>
            </a>
        </div>

        
        <form class="sesion" onSubmit="{{url_for('user_bp.registro')}}" method="POST">
            
            <p>ROL:</p>
            <select type="text" placeholder="nombre" name="ROL"/>
                <option value="usuario">usuario</option>
                <option value="administrador" >administrador</option>
            </select>
            <p>Nombre:</p>
            <input type="text" placeholder="nombre" name="NOMBRE"/>

            <p>Correo:</p>
            <input type="text" placeholder="correo" name="CORREO"/>

            <p>Contraseña:</p>
            <input type="password" placeholder="contrasena" name="CONTRASENA"/>

            
            <button type="submit">
                Registrarse
            </button>
          
        </form>

        <div class="imagen">
            <div class="title">
                !Bienvenido usuario nuevo! 😃
            </div>
            <div class="logo">
                <img src="{{ url_for('static', filename='img/logo.png') }}" alt="" />
            </div>
        </div>

    </div>
    
</body>
</html>

templates/Usuario/Ajustes_u.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Ajustes usuario</title>
    <link rel="stylesheet" href="../../../css/Usuario/Ajustes_u.css">
    <link rel="stylesheet" href="../../../css/Navbar.css">
</head>
<body>

    <div class="ajustes_u">

        <!--Navbar--> 
      <div class="Navbar" >

        <div class="item" onClick={goToAjustes}>
            <img src="../../../img/configuracion.png" alt="casa" class="" />
            <p>Ajustes</p>
        </div>
        <div class="item" onClick={goToInicio}>

            <img src="../../../img/casas.png" alt="casa" class="" />
            <p>Inicio</p>
        </div>

        <div class="item" onClick={goToNotificaciones}>
            <img src="../../../img/notificacion.png" alt="casa" class="" />
            <p>Notificaciones</p>
        </div>

      </div>
        
                <div class="body">
                    <div class="menu">
                      <p onClick={goToCuenta}>Cuenta</p>
                      <p onClick={goToMesas}>Mesas</p>
                      <p onClick={goToInicio}>Cerrar Sesion</p>
                    </div>
                </div>
        
            </div>
    
</body>
</html>

templates/Usuario/Cambio_reserva.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../../css/Usuario/Cambio_reserva.css">
    <link rel="stylesheet" href="../../css/Volver.css">
    <title>Cambio reserva</title>
</head>
<body>


    <div class="cambio_reserva">


        <!--Volver-->
        <div class="header_volver">
            <a class="volver" href="../pantallas/index.html">
                <img src="../../img/flecha.png" alt=""/>
            </a>
        </div>

        <div class="body">
            <div class="horario">

                <div class="titulo" onClick={goToPenalizacion}>Mesa 4</div>
                <div class="plazas">
                    <div class="circle"></div>
                    <div class="titulo" >Plazas disponibles</div>

                    <select name="" id="">
                        <option class='ok_option' value="7-9">7 pm - 9 pm</option>
                        <option class='ok_option' value="7-9">7 pm - 9 pm</option>
                        <option class='ok_option'value="7-9">7 pm - 9 pm</option>
                        <option class='ok_option' value="7-9">7 pm - 9 pm</option>
                        <option class='no_option' value="7-9">7 pm - 9 pm</option>
                    </select>
                </div>
                <button class="boton" onClick={goToReservaExistosa}>
                Reservar
                </button>

            </div>

            

            <div class="imagen">
            <img src="../../img/fondo_mesa.png" alt="" onClick={goToReservaFallida} />
            </div>
        </div>
    </div>
    
</body>
</html>

templates/Usuario/Error_reserva.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../../css/Usuario/Error_reserva.css">
    <link rel="stylesheet" href="../../css/Volver.css">

    <title>Error al reservar</title>
</head>
<body>
    
    <div class="error">
        

        <!--Volver-->
        <div class="header_volver">
            <a class="volver" href="../pantallas/index.html">
                <img src="../../img/flecha.png" alt=""/>
            </a>

        </div>
        <div class="body">
            <div class="error">

                <p class="erno">
                    Error al realizar la reserva
                </p>

                <p class="hora">
                    2:00 pm - 4:00 p.m
                </p>

                <button class="boton" onClick={goToHome}>
                    Intente nuevamente
                </button>
            </div>

            <div class="imagen">
                <img src="../../img/fallout_cansado.png" alt="" />
            </div>
        </div>
    </div>
</body>
</html>

templates/Usuario/Home_u.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{{ url_for('static', filename='css/Usuario/Home_u.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/Navbar.css') }}">
    <title>Home usuario</title>
</head>
<body>

    

  <div class="home_u">
      <!--Navbar--> 
      <div class="Navbar" >

        <div class="item" onClick={goToAjustes}>
            <img src="{{url_for("static",filename="img/configuracion.png")}}" alt="casa" class="" />
            <p>Ajustes</p>
        </div>
        <div class="item" onClick={goToInicio}>

            <img src="{{url_for("static",filename="img/casas.png")}}" alt="casa" class="" />
            <p>Inicio</p>
        </div>

        <div class="item" onClick={goToNotificaciones}>
            <img src="{{url_for("static",filename="img/notificacion.png")}}" alt="casa" class="" />
            <p>Notificaciones</p>
        </div>

      </div>
  
        <div class="body_home">
          <div class="contenido">
  
            <p class="titulo">¡Bienvenido de nuevo Dick Shawns!</p>
  
              <div class="mini_target" onClick={goToReservas}>
  
                  <img src="{{url_for("static",filename="img/Iconos_perfil/mesa.png")}}" alt="" />
                  <p class="info">Mis reservas</p>
  
              </div>
            
          </div>
  
  
          <div class="imagen">
            <img src="{{url_for("static",filename="img/usuario.jpg")}}" alt="" />
          </div>
        </div>
  
      </div>
</body>
</html>

templates/Usuario/Mesas_disponibles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>
    <link rel="stylesheet" href="../../css/Navbar.css">
    <link rel="stylesheet" href="../../css/Usuario/Mesas_disponibles.css">
    <link rel="stylesheet" href="../../css/Usuario/Searchbar.css">
</head>
<body>

    <div class="mesas_disponibles">
    <!--Navbar--> 

    <div class="Navbar" >
        <div class="item" onClick={goToAjustes}>
            
            <img src="../../img/configuracion.png" alt="casa" class="" />
            <p>Ajustes</p>
        </div>
        <div class="item" onClick={goToInicio}>

            <img src="../../img/casas.png" alt="casa" class="" />
            <p>Inicio</p>
        </div>

        <div class="item" onClick={goToNotificaciones}>
            <img src="../../img/notificacion.png" alt="casa" class="" />
            <p>Notificaciones</p>
        </div>

      </div>




        <!-- Search bar -->
        <div class="searchbar">
      
            <input type="text" placeholder='Buscar'/>
            <button>
                Buscar
            </button>

        </div>


        <!--Body y targetas-->
        <div class="body">

            <div class="target" onClick={goToNoDisponibles}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />
                <img class="cartel" src="../../img/cerrado.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>

            <div class="target" onClick={goToReserva}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>
            <div class="target" onClick={goToReserva}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>
            <div class="target" onClick={goToReserva}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>
            <div class="target" onClick={goToReserva}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>
            <div class="target" onClick={goToReserva}>

                <img class="imagen" src="../../img/fondo_mesa.png" alt="" />

                <p class="titulo">Mesa 1</p>

                <button class="boton">
                    Ver disponibilidad
                </button>
            </div>

            </div>

    </div>
    
</body>
</html>

templates/Usuario/Mesas_reserva.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../../css/Usuario/Mesas_reserva.css">
    <link rel="stylesheet" href="../../css/Navbar.css">
    <title>Mesas reservadas</title>
</head>
<body>
    <div class="mesas_reserva">
    <!--Navbar--> 
      <div class="Navbar" >
        <div class="item" onClick={goToAjustes}>

            <img src="../../img/configuracion.png" alt="casa" class="" />
            <p>Ajustes</p>
        </div>
        <div class="item" onClick={goToInicio}>

            <img src="../../img/casas.png" alt="casa" class="" />
            <p>Inicio</p>
        </div>

        <div class="item" onClick={goToNotificaciones}>
            <img src="../../img/notificacion.png" alt="casa" class="" />
            <p>Notificaciones</p>
        </div>

      </div>

        <div class="titulo">
            Tus reservas 😃
        </div>

        <div class="body">


            <div class="target" onClick={goToReserva}>

                <div class="img">
                    <img src="../../img/fondo_mesa.png" alt="" />
                </div>

                <div class="info">
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>

            <div class="target" onClick={goToReserva}>

                <div class="img">
                    <img src="../../img/fondo_mesa.png" alt="" />
                </div>

                <div class="info">
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>

            <div class="target" onClick={goToReserva}>

                <div class="img">
                    <img src="../../img/fondo_mesa.png" alt="" />
                </div>

                <div class="info">
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>

            <div class="target" onClick={goToReserva}>

                <div class="img">
                    <img src="../../img/fondo_mesa.png" alt="" />
                </div>

                <div class="info">
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>

            <div class="target" onClick={goToReserva}>

                <div class="img">
                    <img src="../../img/fondo_mesa.png" alt="" />
                </div>

                <div class="info" >
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>

            <div class="target" onClick={goToHacerReserva}>

                <div class="new">
                    +
                </div>

                <div class="info">
                    <p>Dia: 07 de marzo </p>
                    <p>Mesas: Mesa #2 </p>
                    <p>Horario: 2:00 pm 4:00 p.m</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/Usuario/No_disponibles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="../../css/Usuario/No_disponibles.css">
    <link rel="stylesheet" href="../../css/Volver.css">
    <title>Mesa no disponible</title>
</head>
<body>


    <div class="no_disponibles">
        <!--Volver-->
        <div class="header_volver">
            <a class="volver" href="../pantallas/index.html">
                <img src="../../img/flecha.png" alt=""/>
            </a>
        </div>


        <div class="body">
          <div class="info">
                  <h3>Mesa 3</h3>
                  <li>¡ Todas ras reservas ya fueron agendadas ! 😲 </li>
                  

                  <button class="boton" onClick={goToMenu}>
                      Volver 
                  </button>

          </div>

          <div class="imagen">

                  <img src="../../img/fondo_mesa.png" alt="" class="debajo"/>
                  <img src="../../img/cerrado.png" alt="" class="encima"/>
                  
          </div>
        </div>

    </div>
    
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!-- Favicon -->
        <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='img/logo.png') }}">
        <!-- Estilos -->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/index.css') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"/>
    
        <!-- JS -->
        <script src="{{ url_for('static', filename='js/index.js') }}"></script>
    
        <title>Home</title>
    </head>
<body>

    <div class="Container">
        
    
        <div class="Header_i">
            <div class="Logo">
                <img 
                href=""
                src="{{ url_for('static', filename='img/logo.png') }}" alt="" />
            </div>
            <div class="titulo">
                BBQ EL REAL 🔥 
            </div>
            <div class="Nav">

                <a href="{{url_for('user_bp.registro')}}" class="item" value="Registro">Register</a>
                <a href="{{url_for('login')}}" class="item" value="Login">Login</a>
                <a href="https://www.facebook.com/elahumaderocolima/?locale=es_LA" class="item" value="Informacion">Information</a>
            </div>
        </div>
    
        <div class="Body">
            <div class="Image">
                <img src="{{ url_for('static', filename='img/comida/camaron.jpg') }}" alt="" />
            </div>
    
            <div class="Info">
                <h4 class="titulo">Sobre nosotros </h4>
                <p class="info">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Debitis labore fugiat iure! Tempora, 
                    voluptatem minus facere amet 
                    libero illo dolorem earum, expedita modi fugit labore dicta eum exercitationem laborum unde.
                </p>
    
                <Button class="Register" onClick="goToRegistro" color="Register primary">
                    Haz clic aquí
                </Button>
            </div>
        </div>
    
        <div class="Footer">
            <img src="{{ url_for('static', filename='img/footer_image.jpg') }}" alt="" class="imagen" />
            <div class="info">
                <p>Direccion: calle #</p>
                <p>Correo: </p>
                <p>Constitucion: </p>
                <p>Numero: </p>
            </div>
            <div class="Social">
                <p>Síguenos en redes</p>
                <img src="{{ url_for('static', filename='img/twitter.png') }}" alt="" class="item" onClick="window.location.href = 'https://x.com/smokebbquk'" />
                <img src="{{ url_for('static', filename='img/Intagram.png') }}" alt="" class="item" onClick="window.location.href = 'https://www.instagram.com/real_smoke_el_ahumadero/?__d=11' " />
                <img src="{{url_for('static', filename='img/facebook.png')}}" alt="" class="item" onClick="window.location.href = 'https://www.facebook.com/elahumaderocolima/?locale=es_LA'  " />
            </div>
        </div>
    </div>
    
</body>
</html>